### PR TITLE
Feature/languages

### PR DESCRIPTION
**Pull request by dapsych0**
Updated languages, pulled from origin newest blog post and added team member.

### CODE REVIEW

**Comment by fmaussion** [comment]
:confetti_ball: This is so great! I don't know how I can thank you for this, I'll stay in touch with Bea and we will find a way.

I am able to build the page locally (it looks great! :star_struck:), but gitub pages fails with:

The tag `translate_file` on line 1 in `about.md` is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

This brought me to this: https://github.com/github/pages-gem/issues/401 . It seems that github pages does not support the `jekyll-multiple-languages-plugin` aaaaaaaarg! I might have to build the page locally or using another service than github pages :-1:

**Comment by fmaussion** [comment]
yes, or I'll move to https://www.netlify.com/ ... Do you have experience with the latter? Seems quite easy.

**Comment by fmaussion** [comment]
OK after some more research the easiest will be to build locally and push to github. I'll look into it this week-end. THANKS AGAIN!

**Comment by bearecinos** [comment]
did you managed @fmaussion ?? with the plugin?

**Comment by fmaussion** [comment]
Yes I have to build the site locally and push it after each change (instead of letting github build it) but this is a very minor annyoance in comparison to the gain. The page is now available with translate: https://agroclim-huaraz.info

**Comment by bearecinos** [comment]
cool I can commit Spanish corrections once and a while :) no problem

**Pull request merged**
